@startuml

title __APP's Class Diagram__\n

  namespace com.ranferi.ssrsi {
    class com.ranferi.ssrsi.BuildConfig {
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace activities {
      class com.ranferi.ssrsi.activities.HomeActivity {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace activities {
      class com.ranferi.ssrsi.activities.PlacePagerActivity {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace activities {
      class com.ranferi.ssrsi.activities.SignInActivity {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace activities {
      class com.ranferi.ssrsi.activities.SignUpActivity {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace api {
      interface com.ranferi.ssrsi.api.APIService {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace api {
      class com.ranferi.ssrsi.api.APIUrl {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.HomeFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.PlaceFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.PlaceListFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.ProfileFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.SearchFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.SearchListFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace fragments {
      class com.ranferi.ssrsi.fragments.VisitedFragment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.PlaceVisitedAdapter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.PlacesAdapter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.PlacesListAdapter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.SharedPrefManager {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.UserAdapter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace helper {
      class com.ranferi.ssrsi.helper.ViewPagerAdapter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Category {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Category$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Comment {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Comment$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Image {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Image$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Name {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Name$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Place {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Place$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Places {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.PlacesResponse {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.PlacesResponse$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Rating {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Rating$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.RealmListParcelConverter {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Types {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.User {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.User$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.UserPlace {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.UserPlace$$Parcelable {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.UserResponse {
      }
    }
  }
  

  namespace com.ranferi.ssrsi {
    namespace model {
      class com.ranferi.ssrsi.model.Users {
      }
    }
  }
  

  namespace io.realm {
    class io.realm.DefaultRealmModule {
    }
  }
  

  namespace io.realm {
    class io.realm.DefaultRealmModuleMediator {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_CategoryRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_CommentRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_CommentRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_CommentRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_ImageRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_ImageRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_ImageRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_NameRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_NameRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_NameRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_PlaceRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_RatingRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_RatingRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_RatingRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxyInterface {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_UserRealmProxy {
    }
  }
  

  namespace io.realm {
    class io.realm.com_ranferi_ssrsi_model_UserRealmProxy$$Parcelable {
    }
  }
  

  namespace io.realm {
    interface io.realm.com_ranferi_ssrsi_model_UserRealmProxyInterface {
    }
  }
  

  com.ranferi.ssrsi.activities.HomeActivity .up.|> android.support.design.widget.NavigationView.OnNavigationItemSelectedListener
  com.ranferi.ssrsi.activities.HomeActivity -up-|> android.support.v7.app.AppCompatActivity
  com.ranferi.ssrsi.activities.PlacePagerActivity -up-|> android.support.v7.app.AppCompatActivity
  com.ranferi.ssrsi.activities.SignInActivity .up.|> android.view.View.OnClickListener
  com.ranferi.ssrsi.activities.SignInActivity -up-|> android.support.v7.app.AppCompatActivity
  com.ranferi.ssrsi.activities.SignUpActivity .up.|> android.view.View.OnClickListener
  com.ranferi.ssrsi.activities.SignUpActivity -up-|> android.support.v7.app.AppCompatActivity
  com.ranferi.ssrsi.fragments.HomeFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.HomeFragment o-- com.ranferi.ssrsi.activities.HomeActivity : mActivity
  com.ranferi.ssrsi.fragments.PlaceFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.PlaceListFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.ProfileFragment .up.|> android.view.View.OnClickListener
  com.ranferi.ssrsi.fragments.ProfileFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.SearchFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.SearchListFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.fragments.SearchListFragment o-- com.ranferi.ssrsi.model.PlacesResponse : mPlacesResponse
  com.ranferi.ssrsi.fragments.VisitedFragment -up-|> android.support.v4.app.Fragment
  com.ranferi.ssrsi.helper.PlaceVisitedAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.ranferi.ssrsi.helper.PlacesAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.ranferi.ssrsi.helper.PlacesListAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.ranferi.ssrsi.helper.UserAdapter -up-|> android.support.v7.widget.RecyclerView.Adapter
  com.ranferi.ssrsi.helper.ViewPagerAdapter -up-|> android.support.v4.view.PagerAdapter
  com.ranferi.ssrsi.model.Category -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Category$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Category$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Category$$Parcelable o-- com.ranferi.ssrsi.model.Category : category$$1
  com.ranferi.ssrsi.model.Comment -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Comment o-- com.ranferi.ssrsi.model.User : user
  com.ranferi.ssrsi.model.Comment$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Comment$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Comment$$Parcelable o-- com.ranferi.ssrsi.model.Comment : comment$$1
  com.ranferi.ssrsi.model.Image -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Image$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Image$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Image$$Parcelable o-- com.ranferi.ssrsi.model.Image : image$$1
  com.ranferi.ssrsi.model.Name -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Name$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Name$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Name$$Parcelable o-- com.ranferi.ssrsi.model.Name : name$$1
  com.ranferi.ssrsi.model.Place -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Place$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Place$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Place$$Parcelable o-- com.ranferi.ssrsi.model.Place : place$$1
  com.ranferi.ssrsi.model.PlacesResponse -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.PlacesResponse$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.PlacesResponse$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.PlacesResponse$$Parcelable o-- com.ranferi.ssrsi.model.PlacesResponse : placesResponse$$1
  com.ranferi.ssrsi.model.Rating -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.Rating$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.Rating$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.Rating$$Parcelable o-- com.ranferi.ssrsi.model.Rating : rating$$1
  com.ranferi.ssrsi.model.RealmListParcelConverter .up.|> org.parceler.TypeRangeParcelConverter
  com.ranferi.ssrsi.model.User -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.User$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.User$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.User$$Parcelable o-- com.ranferi.ssrsi.model.User : user$$1
  com.ranferi.ssrsi.model.UserPlace -up-|> io.realm.RealmObject
  com.ranferi.ssrsi.model.UserPlace o-- com.ranferi.ssrsi.model.Comment : comentarioUsuario
  com.ranferi.ssrsi.model.UserPlace$$Parcelable .up.|> android.os.Parcelable
  com.ranferi.ssrsi.model.UserPlace$$Parcelable .up.|> org.parceler.ParcelWrapper
  com.ranferi.ssrsi.model.UserPlace$$Parcelable o-- com.ranferi.ssrsi.model.UserPlace : userPlace$$1
  com.ranferi.ssrsi.model.UserResponse o-- com.ranferi.ssrsi.model.User : user
  io.realm.DefaultRealmModuleMediator -up-|> io.realm.internal.RealmProxyMediator
  io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_CategoryRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy -up-|> com.ranferi.ssrsi.model.Category
  io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy o-- io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy.CategoryColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_CategoryRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Category$$Parcelable
  io.realm.com_ranferi_ssrsi_model_CommentRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_CommentRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_CommentRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_CommentRealmProxy -up-|> com.ranferi.ssrsi.model.Comment
  io.realm.com_ranferi_ssrsi_model_CommentRealmProxy o-- io.realm.com_ranferi_ssrsi_model_CommentRealmProxy.CommentColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_CommentRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Comment$$Parcelable
  io.realm.com_ranferi_ssrsi_model_ImageRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_ImageRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_ImageRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_ImageRealmProxy -up-|> com.ranferi.ssrsi.model.Image
  io.realm.com_ranferi_ssrsi_model_ImageRealmProxy o-- io.realm.com_ranferi_ssrsi_model_ImageRealmProxy.ImageColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_ImageRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Image$$Parcelable
  io.realm.com_ranferi_ssrsi_model_NameRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_NameRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_NameRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_NameRealmProxy -up-|> com.ranferi.ssrsi.model.Name
  io.realm.com_ranferi_ssrsi_model_NameRealmProxy o-- io.realm.com_ranferi_ssrsi_model_NameRealmProxy.NameColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_NameRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Name$$Parcelable
  io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_PlaceRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy -up-|> com.ranferi.ssrsi.model.Place
  io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy o-- io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy.PlaceColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_PlaceRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Place$$Parcelable
  io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy -up-|> com.ranferi.ssrsi.model.PlacesResponse
  io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy o-- io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy.PlacesResponseColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_PlacesResponseRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.PlacesResponse$$Parcelable
  io.realm.com_ranferi_ssrsi_model_RatingRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_RatingRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_RatingRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_RatingRealmProxy -up-|> com.ranferi.ssrsi.model.Rating
  io.realm.com_ranferi_ssrsi_model_RatingRealmProxy o-- io.realm.com_ranferi_ssrsi_model_RatingRealmProxy.RatingColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_RatingRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.Rating$$Parcelable
  io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy -up-|> com.ranferi.ssrsi.model.UserPlace
  io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy o-- io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy.UserPlaceColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_UserPlaceRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.UserPlace$$Parcelable
  io.realm.com_ranferi_ssrsi_model_UserRealmProxy .up.|> io.realm.com_ranferi_ssrsi_model_UserRealmProxyInterface
  io.realm.com_ranferi_ssrsi_model_UserRealmProxy .up.|> io.realm.internal.RealmObjectProxy
  io.realm.com_ranferi_ssrsi_model_UserRealmProxy -up-|> com.ranferi.ssrsi.model.User
  io.realm.com_ranferi_ssrsi_model_UserRealmProxy o-- io.realm.com_ranferi_ssrsi_model_UserRealmProxy.UserColumnInfo : columnInfo
  io.realm.com_ranferi_ssrsi_model_UserRealmProxy$$Parcelable -up-|> com.ranferi.ssrsi.model.User$$Parcelable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
